[project]
name = "datadec"
version = "0.1.0"
description = "A library to download and process DataDecide datasets from Hugging Face."
readme = "README.md"
authors = [
    { name = "Danielle Rothermel", email = "danielle.rothermel@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "datasets>=5.0.1",
    "dr-ds>=0.1.2",
    "huggingface-hub>=1.3.5",
    "numpy>=2.0.2",
    "orjson>=3.11.2",
    "pandas>=2.3.1",
    "pyarrow>=21.0.0",
    "pydantic>=2.11",
    "srsly>=2.5.1",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["src/datadec"]

[tool.hatch.build.targets.wheel.force-include]
"configs/catalog.toml" = "datadec/configs/catalog.toml"
"configs/olmes.toml" = "datadec/configs/olmes.toml"
"configs/published_results.toml" = "datadec/configs/published_results.toml"
"configs/sources.toml" = "datadec/configs/sources.toml"

[tool.ruff]
include = ["src/**/*.py", "scripts/**/*.py", "tests/**/*.py"]
line-length = 88
cache-dir = ".ruff_cache"
exclude = ["outputs/*", "notebooks/*"]

[tool.uv.sources]
datadec = { workspace = true }

[dependency-groups]
dev = [
    "datadec",
    "pytest>=8.4.1",
    "pytest-postgresql>=7.0.0",
    "ty",
    "typer>=0.20.0",
]
