# Final Step Bump Analysis Configuration
# Replaces plot_bump.py functionality: X=params, Lines=data, final step only

# Analysis parameters
metric: "pile-valppl"
x_axis: "params" 
hue_by: "data"
final_step_only: true

# Data selection - smaller subset for testing
params: ["150M", "300M"]
data: ["C4", "Dolma1.7"]
exclude_data: []
exclude_params: []

# Plot styling
figsize: [12, 8]

# Layout (required by CLI framework, but will create single plot)
rows_and_cols: "data"

# Output
save_dir: "/tmp"