# DataDec plotting configuration example
# Shows how to set up dimensional plots for DataDec data

faceting:
  # Layout strategy - wrap params across grid
  rows_and_cols: params
  max_cols: 3
  
  # Visual encoding
  hue_by: data
  alpha_by: seed
  
  # Fix specific dimensions to focus analysis
  fixed_dimensions:
    metric: pile-valppl
    
  # Restrict to main datasets for readable legends
  exclude_dimensions:
    data: ["pile", "openwebtext", "github", "arxiv"]  # Keep only C4 and Dolma1.7
    
  # Order params from small to large
  ordered_dimensions:
    params: ["150M", "300M", "530M", "750M", "1B"]

legend:
  strategy: grouped
  
plot:
  # Custom sizing for overview plots
  subplot_width: 3.5
  subplot_height: 3.0